project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About" 
        href: about.qmd
      - text: "Hands On Exercise"
        menu: 
          - text: "Hands On Exercise 1.1"
            href: hands-on-exercise/hands-on-exercise-1_1.qmd
          - text: "Hands On Exercise 1.2"
            href: hands-on-exercise/hands-on-exercise-1_2.qmd
          - text: "Hands On Exercise 2.1"
            href: hands-on-exercise/hands-on-exercise-2_1.qmd
          - text: "Hands On Exercise 2.2"
            href: hands-on-exercise/hands-on-exercise-2_2.qmd
          - text: "Hands On Exercise 3.1"
            href: hands-on-exercise/hands-on-exercise-3_1.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

